### PR TITLE
Added cross-env for cross-environment compatibility to the backend

### PR DESCRIPTION
**Pull request by karmabadger**
This is a small addition to the package.json of the backend in order to add the cross-env package and to the "dev" script so that it is compatible with all Operating Systems.

### CODE REVIEW

**Comment by karmabadger** [comment]
Not sure if I was supposed to include the package-lock.json into here tho

**Comment by karmabadger** [comment]
changed the commit to one without the package-lock.json completely.

**Comment by karmabadger** [comment]
> @karmabadger This is great!
> 
> Since we changed the `package.json`, we actually should run `npm i` and include the `package-lock.json`. Then, exactly what is in that `package-lock.json` file will be installed.
> 
> Also, can you make a branch in our repo? Here's steps:
> 
> 1. `git clone git@github.com:engineer-dao/platform.git`
> 2. `cd platform`
> 3. `git checkout -b fix/windows-compatibility`
> 4. `git commit -am "Add cross-env"`
> 5. `git push`
> 6. Come back to Github and make a PR from the branch `fix/windows-compatibility`

I'm not exactly sure what this would be for? I think I would be access denied if I tried to push to git@github.com:engineer-dao/platform.git?

```
git push origin
remote: Permission to engineer-dao/platform.git denied to karmabadger.
fatal: unable to access 'https://github.com/engineer-dao/platform.git/': The requested URL returned error: 403
```

would merging this PR to main work? or perhaps to a fix/windows-compatibility branch?

**Comment by indeavr** [comment]
Hi @karmabadger, thanks for adding this & sorry for the slow response ! 

We need to add a proper contribution guide. I've created an [Issue](https://github.com/engineer-dao/platform/issues/80)

@reisr3 Let's only push the yarn.lock. 

As for the proper flow (in short) - I believe that  working on a fork is preferable:)

All we need is the updated `yarn.lock` & I'll merge this PR.

**Comment by indeavr** [comment]
I'm merging this, thanks @karmabadger  !

**Pull request merged**
